# Generated by Django 4.2.2 on 2023-06-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=30)),
                ('guardian_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('contact_detais', models.IntegerField(max_length=100)),
            ],
        ),
    ]
